### ISSUE TITLE
Improve reproducibility of "deltares_data" catalog sources

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#537]
### Enhancement Description

Updating the meta data section in deltares_data.yml & documentation according to:

```yaml
  meta:
    source_url: zenodo.org/my_dataset # should point to processed data OR original in combi with processing_notes/script
    source_license: CC-BY-3.0
    source_version: vX.X
    paper_ref: Author et al. (year)
    paper_doi: doi
    processing_notes:  <description of process in script OR simple processing steps (e.g. filter / gdalbuildvrt)>
    processing_script: <url to script>
    category: category
```

It should be checked case by case what is required for reproducibility. there are several options:
- publish pre-processed data together with the script on Zenodo (e.g. MODIS_LAI/ MERIT Hydro basins map) and point to this data in `source_url`
- point to scripts in `processing_script` to download and/or process (e.g. ERA5)
- add `processing_notes` for simple processing to filter data (e.g. hydro_lakes) or create a vrt (merit)
- documentation of required data (e.g. bounds is required in the hydrographic region argument unless the basin map and index are present)
- check used data sources in examples (e.g. replace merit_hydro with merit_hydro_ihu).

### ToDo
- [x] identify data sources in deltares_data.yml that need updating
- [x] update meta section
- [ ] if the dataset requires publishing / new scripts (more work) -> create separate issues
- [ ] update docs and examples (also in plugins)

### Additional Context

this is a continuation of #356

**Comment by Tjalling-dejong** [comment]
The following datasets need to be updated:
- CHELSA 1.2 -> 2.1
- COPDEM 2021_1 -> 2022_1
- E-OBS 25.0e -> 28.0e
- Esa world cover v100 -> v200
- FABDEM v1.0 -> v1.2
- GADM 3.6 -> 4.1
- GEBCO 2020 -> 2023
- GHS_POP R2019A_v1.0 -> R2023A
- GHS_SMOD  R2016A_v1.0 -> R2023A
- GLOFAS v31? -> v4.0
- GLW v3 -> v4
- GSWO v1_1_2019 -> v2021
- Mdt_cnes_cls18 -> cls22
- MODIS LAI MCD15A3H V006- > MCD15A3H V061
- SM2RAIN_ASCAT v1.4 -> v2.1
- Worldclim 2.0 -> worldclim 2.1
- World settlement footprint 2015 -> 2019 version
